services:
  mongodb:
    image: mongo:7
    container_name: membership_mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - membership_mongo_data:/data/db

volumes:
  membership_mongo_data: